# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vphongph <vphongph@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/24 21:12:59 by vphongph          #+#    #+#              #
#    Updated: 2018/11/15 03:57:15 by vphongph         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = display_file.c
RM = /bin/rm -f
NAME = ft_display_file
O = *.o

all: 
	@gcc -Wall -Wextra -Werror $(SRC) -o $(NAME)

clean: 
	@$(RM) $(O)

fclean: clean 
	@$(RM) $(NAME)